<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite configfailurepolicy="continue" thread-count="4" parallel="tests" name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <test thread-count="4" parallel="tests" name="Test(failed)">
    <classes>
      <class name="testcase.homePageTestCase">
        <methods>
          <include name="beforeMethod"/>
          <include name="beforeClass"/>
          <include name="verifyHomePage"/>
          <include name="beforeTest"/>
          <include name="afterTest"/>
        </methods>
      </class> <!-- testcase.homePageTestCase -->
    </classes>
  </test> <!-- Test(failed) -->
  <test thread-count="4" parallel="tests" name="Test2(failed)">
    <classes>
      <class name="testcase.homePageTestCase">
        <methods>
          <include name="beforeMethod"/>
          <include name="beforeClass"/>
          <include name="verifyHomePage"/>
          <include name="beforeTest"/>
          <include name="afterTest"/>
        </methods>
      </class> <!-- testcase.homePageTestCase -->
    </classes>
  </test> <!-- Test2(failed) -->
</suite> <!-- Failed suite [Suite] -->
